# Generated by Django 5.0.2 on 2024-02-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Premium", "Premium"),
                            ("Pro", "Pro"),
                        ],
                        default="Basic",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("amount", models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="market.price",
            ),
        ),
    ]
