# Generated by Django 5.0 on 2024-01-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="articles"),
        ),
    ]
