# Generated by Django 5.0 on 2024-01-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_article_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="language",
            field=models.CharField(choices=[("Fr", "Fr"), ("En", "En")], max_length=20),
        ),
    ]
