# Generated by Django 5.0.2 on 2024-02-29 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_article_content_alter_article_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RenameField(
            model_name="article",
            old_name="content",
            new_name="article",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="language",
            new_name="langue",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="tag",
            new_name="theme",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="title",
            new_name="titre",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.AddField(
            model_name="comment",
            name="personne",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
