# Generated by Django 5.0.2 on 2024-02-29 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_article_options_rename_content_article_article_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="article",
            new_name="body",
        ),
    ]
