# Generated by Django 5.0.2 on 2024-02-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="limited",
            field=models.BooleanField(db_default=True),
        ),
    ]
