# Generated by Django 5.0.2 on 2024-02-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_alter_price_limited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="limited",
            field=models.BooleanField(default=True),
        ),
    ]
