# Generated by Django 5.0.2 on 2024-02-21 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0003_alter_price_limited"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Price",
        ),
    ]
