# Generated by Django 5.0 on 2024-01-23 14:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_admin_team_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedIn_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users",
                verbose_name=django.db.models.expressions.CombinedExpression(
                    models.F("username"), "+", models.Value("_pic")
                ),
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
