# Generated by Django 5.0 on 2024-01-23 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_user_thumbnail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
