# Generated by Django 5.0.2 on 2024-02-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_delete_admin_delete_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Simple", "Simple"), ("Team", "Team"), ("Admin", "Admin")],
                default="Simple",
                max_length=20,
            ),
        ),
    ]
