# Generated by Django 5.0.2 on 2024-02-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Simple", "Simple"),
                    ("Team", "Team"),
                    ("Admin", "Admin"),
                    ("CA", "CA"),
                    ("Compt", "Compt"),
                ],
                default="Simple",
                max_length=20,
            ),
        ),
    ]
